
User.create!([
  {first_name: "Mark", last_name: "Butcher", phone_number: "312-988-2737", email: "mark@email.com", password: "password"},
  {first_name: "Barbara", last_name: "Jackson", phone_number: "312-898-2657", email: "barbara@email.com", password: "password"},
  {first_name: "Tyrone", last_name: "Hill", phone_number: "312-233-7123", email: "tyrone@email.com", password: "password"},
  {first_name: "Amanda", last_name: "Bryant", phone_number: "773-665-7875", email: "amanda@email.com", password: "password"},
  {first_name: "Mark", last_name: "Butcher", phone_number: "312-988-2737", email: "mark@email.com", password: "password"},
  {first_name: "Barbara", last_name: "Jackson", phone_number: "312-898-2657", email: "barbara@email.com", password: "password"},
  {first_name: "Tyrone", last_name: "Hill", phone_number: "312-233-7123", email: "tyrone@email.com", password: "password"},
  {first_name: "Amanda", last_name: "Bryant", phone_number: "773-665-7875", email: "amanda@email.com", password: "password"}
])

Doctor.create!([
  {first_name: "Horace", last_name: "Grant", phone_number: "708-988-7656", email: "horace@email.com", user_id: 3},
  {first_name: "Peter", last_name: "Jang", phone_number: "312-578-9011", email: "peter@email.com", user_id: 1},
  {first_name: "Myles", last_name: "Woener", phone_number: "815-676-9899", email: "myles@email.com", user_id: 2},
  {first_name: "Kate", last_name: "Janssen", phone_number: "224-878-6336", email: "kate@email.com", user_id: 4},
  {first_name: "Horace", last_name: "Grant", phone_number: "708-988-7656", email: "horace@email.com", user_id: 3},
  {first_name: "Peter", last_name: "Jang", phone_number: "312-578-9011", email: "peter@email.com", user_id: 1},
  {first_name: "Myles", last_name: "Woener", phone_number: "815-676-9899", email: "myles@email.com", user_id: 2},
  {first_name: "Kate", last_name: "Janssen", phone_number: "224-878-6336", email: "kate@email.com", user_id: 4}
])

MedicalCategory.create!([
  {name: "Infection", description: "text"},
  {name: "Allergies", description: "text"},
  {name: "Stomach pain", description: "text"},
  {name: "Aches and pains", description: "text"}
])

Product.create!([
  {name: "Claritin", medical_category_id: 4, description: "Claritin (loratadine) is an antihistamine that reduces the effects of natural chemical histamine in the body. Histamine can produce symptoms of sneezing, itching, watery eyes, and runny nose.\n\nClaritin is used to treat sneezing, runny nose, watery eyes, hives, skin rash, itching, and other cold or allergy symptoms.\n\nClaritin is also used to treat skin hives and itching in people with chronic skin reactions.", side_effects: "\nGet emergency medical help if you have signs of an allergic reaction to Claritin: hives; difficult breathing; swelling of your face, lips, tongue, or throat.\n\nStop using Claritin and call your doctor at once if you have:\n\nfast or uneven heart rate;\nsevere headache; or\na light-headed feeling, like you might pass out;\nCommon Claritin side effects may include:\n\nheadache;\nfeeling tired or drowsy;\nstomach pain, vomiting;\ndry mouth; or\nfeeling nervous or hyperactive.\n\n"},
  {name: "Penicillin", medical_category_id: 2, description: "Penicillin V is an antibiotic in the penicillin group of drugs. It fights bacteria in your body.\n\nPenicillin V is used to treat many different types of infections caused by bacteria, such as ear infections,.\n\nPenicillin V may also be used for other purposes not listed in this medication guide.\n\n", side_effects: "Get emergency medical help if you have any of these signs of an allergic reaction to penicillin V: hives; difficulty breathing; swelling of your face, lips, tongue, or throat. Call your doctor at once if you have any of these serious side effects:\n\ndiarrhea that is watery or bloody;\nfever, chills, body aches, flu symptoms;\neasy bruising or bleeding, unusual weakness;\nurinating less than usual or not at all;\nsevere skin rash, itching, or peeling;\nagitation, confusion, unusual thoughts or behavior; or\nseizure (black-out or convulsions).\n"},
  {name: "Pepto-Bismol", medical_category_id: 1, description: "Pepto-Bismol is used to treat diarrhea and relieve the symptoms of an upset stomach. These symptoms can include heartburn, nausea, and indigestion. They can also include gas, belching, and a feeling of fullness. The active ingredient in Pepto-Bismol is called bismuth subsalicylate. It belongs to the drug class called salicylates. Pepto-Bismol is available in regular strength as a caplet, chewable tablet, and liquid. It’s available in maximum strength as a liquid. All forms are taken by mouth.", side_effects: "Get emergency medical help if you have any of these signs of an allergic reaction: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.\n\nStop taking this medicine and call your doctor at once if you have:\n\nhearing loss or ringing in your ears;\ndiarrhea lasting longer than 2 days; or\nworsened stomach symptoms.\nCommon side effects include:\n\nconstipation;\ndark colored stools; or\nblack or darkened tongue.\nThis is not a complete list of side effects and others may occur. Call your doctor for medical advice about side effects. You may report side effects to FDA at 1-800-FDA-1088.\n\n"},
  {name: "Pepto-Bismol", medical_category_id: 1, description: "Pepto-Bismol is used to treat diarrhea and relieve the symptoms of an upset stomach. These symptoms can include heartburn, nausea, and indigestion. They can also include gas, belching, and a feeling of fullness. The active ingredient in Pepto-Bismol is called bismuth subsalicylate. It belongs to the drug class called salicylates. Pepto-Bismol is available in regular strength as a caplet, chewable tablet, and liquid. It’s available in maximum strength as a liquid. All forms are taken by mouth.", side_effects: "Get emergency medical help if you have any of these signs of an allergic reaction: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.\n\nStop taking this medicine and call your doctor at once if you have:\n\nhearing loss or ringing in your ears;\ndiarrhea lasting longer than 2 days; or\nworsened stomach symptoms.\nCommon side effects include:\n\nconstipation;\ndark colored stools; or\nblack or darkened tongue.\nThis is not a complete list of side effects and others may occur. Call your doctor for medical advice about side effects. You may report side effects to FDA at 1-800-FDA-1088.\n\n"},
  {name: "Zantac", medical_category_id: 1, description: "Zantac (ranitidine) belongs to a group of drugs called histamine-2 blockers. Zantac works by reducing the amount of acid your stomach produces.\n\nZantac is used to treat and prevent ulcers in the stomach and intestines. It also treats conditions in which the stomach produces too much acid, such as Zollinger-Ellison syndrome. Zantac also treats gastroesophageal reflux disease (GERD) and other conditions in which acid backs up from the stomach into the esophagus, causing heartburn.\n\nZantac may also be used for other purposes not listed in this medication guide.", side_effects: "Stop using Zantac and get emergency medical help if you have any of these signs of an allergic reaction to Zantac: hives; difficulty breathing; swelling of your face, lips, tongue, or throat. Stop taking Zantac and call your doctor at once if you have a serious side effect such as:\n\nchest pain, fever, feeling short of breath, coughing up green or yellow mucus;\neasy bruising or bleeding, unusual weakness;\nfast or slow heart rate;\nproblems with your vision;\nfever, sore throat, and headache with a severe blistering, peeling, and red skin rash; or\nnausea, stomach pain, low fever, loss of appetite, dark urine, clay-colored stools, jaundice (yellowing of the skin or eyes)."},
  {name: "Aleve", medical_category_id: 3, description: "Aleve (naproxen) is a nonsteroidal anti-inflammatory drug (NSAID). Naproxen works by reducing hormones that cause inflammation and pain in the body.\n\nAleve is used to temporarily relieve minor aches and pains due to arthritis, muscular aches, backache, menstrual cramps, headache, toothache,and the common cold. Aleve is also used to temporarily reduce fever.\n\nAleve may also be used for purposes not listed in this medication guide.\n\n", side_effects: "Common Aleve side effects may include:\n\nindigestion, heartburn, stomach pain, nausea;\nheadache, dizziness, drowsiness;\nbruising, itching, rash;\nswelling; or\nringing in your ears.\nThis is not a complete list of side effects and others may occur. Call your doctor for medical advice about side effects. You may report side effects to FDA at 1-800-FDA-1088."},
  {name: "Advil", medical_category_id: 3, description: "Advil (ibuprofen) is a nonsteroidal anti-inflammatory drug (NSAID). Ibuprofen works by reducing hormones that cause inflammation and pain in the body.\n\nAdvil is used to reduce fever and treat pain or inflammation caused by many conditions such as headache, toothache, back pain, arthritis, menstrual cramps, or minor injury.\n\nAdvil is used in adults and children who are at least 6 months old.", side_effects: "Common Advil side effects may include:\n\nupset stomach, mild heartburn, nausea, vomiting;\nbloating, gas, diarrhea, constipation;\ndizziness, headache, nervousness;\nmild itching or rash; or\nringing in your ears.\nThis is not a complete list of side effects and others may occur. Call your doctor for medical advice about side effects. You may report side effects to FDA at 1-800-FDA-1088.\n\n"},
  {name: "Tylenol", medical_category_id: 3, description: "Tylenol (acetaminophen) is a pain reliever and a fever reducer.\n\nTylenol is used to treat many conditions such as headache, muscle aches, arthritis, backache, toothaches, colds, and fevers.\n\nTylenol may also be used for purposes not listed in this medication guide.\n\n", side_effects: "Get emergency medical help if you have any signs of an allergic reaction to Tylenol: hives; difficulty breathing; swelling of your face, lips, tongue, or throat.\n\nIn rare cases, Tylenol may cause a severe skin reaction that can be fatal. This could occur even if you have taken acetaminophen in the past and had no reaction. Stop taking this medicine and call your doctor right away if you have skin redness or a rash that spreads and causes blistering and peeling. If you have this type of reaction, you should never again take any medicine that contains acetaminophen.\n\nStop taking this medication and call your doctor at once if you have:\n\nnausea, upper stomach pain, itching, loss of appetite;\ndark urine, clay-colored stools; or\njaundice (yellowing of the skin or eyes).\nThis is not a complete list of side effects and others may occur. Call your doctor for medical advice about side effects. You may report side effects to FDA at 1-800-FDA-1088.\n\n"},
  {name: "ibuprofen", medical_category_id: 3, description: "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID). It works by reducing hormones that cause inflammation and pain in the body.\n\nIbuprofen is used to reduce fever and treat pain or inflammation caused by many conditions such as headache, toothache, back pain, arthritis, menstrual cramps, or minor injury.\n\nIbuprofen is used in adults and children who are at least 6 months old.\n\n\n", side_effects: "\nGet emergency medical help if you have signs of an allergic reaction to ibuprofen: sneezing, runny or stuffy nose; wheezing or trouble breathing; hives; swelling of your face, lips, tongue, or throat.\nGet emergency medical help if you have signs of a heart attack or stroke: chest pain spreading to your jaw or shoulder, sudden numbness or weakness on one side of the body, slurred speech, leg swelling, feeling short of breath.\nStop using ibuprofen and call your doctor at once if you have:\nchanges in your vision;\nshortness of breath (even with mild exertion);\nswelling or rapid weight gain;\nthe first sign of any skin rash, no matter how mild;\nsigns of stomach bleeding - bloody or tarry stools, coughing up blood or vomit that looks like coffee grounds;\nliver problems - nausea, upper stomach pain, itching, tired feeling, flu-like symptoms, loss of appetite, dark urine, clay-colored stools, jaundice (yellowing of the skin or eyes);\nkidney problems - little or no urinating, painful or difficult urination, swelling in your feet or ankles, feeling tired or short of breath;\n"}
])

Prescription.create!([
  {user_id: 3, product_id: 2, amount: 4, dosage: "Adults and teenagers who weigh at least 110 pounds (50 kilograms): Do not take more than 1000 milligrams (mg) at one time. Do not take more than 4000 mg in 24 hours.\nChildren younger than 12 years old: Do not take more than 5 doses of acetaminophen in 24 hours. Use only the number of milligrams per dose that is recommended for the child's weight and age. Use exactly as directed on the label.\nAvoid also using other medicines that contain acetaminophen, or you could have a fatal overdose.", schedule: nil},
  {user_id: 3, product_id: 4, amount: 7, dosage: "The recommended dose for children ages 2 to 5 years is 5 mg taken once a day. This is equivalent to one teaspoonful or 5 ml of Claritin syrup or one Claritin chewable tablet. However, be sure that you are taking the appropriate drug formulation. Take note that Claritin is available in different drug formulations therefore be sure to read the prescription label carefully before starting the medication and before taking each dose. Younger children may be more sensitive to the effects of this drug and hence may be prone to drug overdose.\n\nSource: Claritin Dosage (Loratadine) - Drugsdb.com http://www.drugsdb.com/otc/claritin/claritin-dosage/", schedule: nil},
  {user_id: 2, product_id: 4, amount: 18, dosage: "", schedule: "1m"},
  {user_id: 4, product_id: 4, amount: 20, dosage: "2", schedule: "1d"},
  {user_id: 4, product_id: 3, amount: 20, dosage: "2", schedule: "1m"},
  {user_id: 2, product_id: 7, amount: 19, dosage: "Naproxen is used to relieve pain from various conditions such as headache, muscle aches, dental pain, menstrual cramps, or arthritis. It is also used to reduce fever and relieve minor aches and pain due to the common cold or flu. This medication is known as a nonsteroidal anti-inflammatory drug (NSAID). It works by blocking your body's production of certain natural substances that cause inflammation. This effect helps to decrease swelling, pain, or fever.\n\n", schedule: "6h"},
  {user_id: 1, product_id: 3, amount: 20, dosage: nil, schedule: "1m"},
  {user_id: 3, product_id: 5, amount: 30, dosage: "Patients should be well hydrated prior to infusion to reduce the risk of renal adverse events.\n-Doses should be infused over at least 30 minutes.\n\nUses: For the management of mild to moderate pain; and the management of moderate to severe pain as an adjunct to opioid analgesics\n\nOral:\n200 to 400 mg orally every 4 to 6 hours as needed\nMaximum dose: 3200 mg/day (prescription strength); 1200 mg/day (over-the-counter)\n", schedule: "1m"},
  {user_id: 2, product_id: 6, amount: 18, dosage: "", schedule: "1m"},
  {user_id: 3, product_id: 8, amount: 20, dosage: "Begin by taking 1-2 tablets, swallowed whole with water. One tablet will often be adequate for mild pain, but for more severe pain you may require two tablets. Repeat dose if necessary after 4-6 hours.\nDo not exceed 6 tablets in 24 hours.\nDo not give to children under 12 years.\nSide effects may be minimised by using the smallest dose for the shortest duration of time.", schedule: nil},
  {user_id: 2, product_id: 3, amount: 27, dosage: "", schedule: "1m"},
  {user_id: 2, product_id: 2, amount: 20, dosage: "", schedule: "1m"},
  {user_id: 2, product_id: 5, amount: 17, dosage: "", schedule: "1m"},
  {user_id: 2, product_id: 4, amount: nil, dosage: "", schedule: "1m"},
  {user_id: 2, product_id: 8, amount: 13, dosage: "Usual Adult Dose for Headache:\nTake two in the morning\nStudy (n=34) - Prevention of Electroconvulsive therapy (ECT)-induced headache:\n600 mg orally 90 minutes prior to the initial ECT session\n\nUsual Adult Dose for Pain:\n\nOral: Mild to moderate pain:\n200 to 400 mg orally every 4 to 6 hours as needed. Doses greater than 400 mg have not been proven to provide greater efficacy.\n\nIV: (Patients should be well hydrated before IV ibuprofen administration):\nPain: 400 to 800 mg intravenously over 30 minutes every 6 hours as needed.\n\nUsual Adult Dose for Fever:\n\nOral:\n200 to 400 mg orally every 4 to 6 hours as needed.\n", schedule: "1m"}
])
